import horsePackage from '@/render/paperRig/generated/horse.json'
import type { PaperRigSpec } from '@/render/paperRig/types'

// Generated by `npm run import-paper-rigs -- <workbench> horse`. Kept in its
// own module so the battle runtime does not pull other gallery specimens into
// the main application chunk.
export const WORKBENCH_V2_HORSE = horsePackage as unknown as PaperRigSpec
export const WORKBENCH_HORSE = WORKBENCH_V2_HORSE
