import humanoidPackage from '@/render/paperRig/generated/humanoid.json'
import rhinoPackage from '@/render/paperRig/generated/rhino.json'
import { WORKBENCH_V2_HORSE } from '@/render/paperRig/horse'
import type { PaperRigSpec } from '@/render/paperRig/types'

// Generated by `npm run import-paper-rigs -- <workbench> <models...>`. The
// workbench owns the broader authoring schema; these files are its validated,
// runtime-only paper-rig/1@1.1 projection packages.
export const WORKBENCH_V2_HUMANOID = humanoidPackage as unknown as PaperRigSpec
export const WORKBENCH_V2_RHINO = rhinoPackage as unknown as PaperRigSpec

export const PAPER_RIG_SPECIMENS = {
  horse: WORKBENCH_V2_HORSE,
  humanoid: WORKBENCH_V2_HUMANOID,
  rhino: WORKBENCH_V2_RHINO,
} as const

export type PaperRigSpecimenId = keyof typeof PAPER_RIG_SPECIMENS
